# Generated by Django 6.0.6 on 2026-06-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_constraints_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(blank=True, help_text='Description of input format'),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256, help_text='Memory limit in MB'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(blank=True, help_text='Description of output format'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1.0, help_text='Time limit in seconds'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
