# Generated by Django 6.0.6 on 2026-06-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_input_format_problem_memory_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='execution_time',
            field=models.FloatField(blank=True, help_text='Execution time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_used',
            field=models.IntegerField(blank=True, help_text='Memory used in KB', null=True),
        ),
    ]
